version: "3.3"
services:
  generator:
    image: newg_protocols/generator
    build: ./generator
    volumes:
      # プロトコルジェネレータスクリプトと定義
      - ./generator/app:/app
      - ./spec.yml:/app/spec.yml
      # nodejs 出力先 (/generate/nodejs/xxx)
      - ../api/app:/generate/nodejs/api/
      - ../matching/app:/generate/nodejs/matching/
      - ../test/test-matching-client/app:/generate/nodejs/test-matching-client/
      - ../test/test-services-client/app:/generate/nodejs/test-services-client/
      - ../test/test-services-server/app:/generate/nodejs/test-services-server/
      - ../test/test-webapi-client/app:/generate/nodejs/test-webapi-client/
      # C# 出力先 (/generate/cs/xxx)
      - ../../Assets/Game/Scripts/Services:/generate/cs/Assets/

