version: "3.3"
services:
  generator:
    image: newg_protocols/generator
    build: ./generator
    volumes:
      # ジェネレータスクリプトと定義
      - ./generator/app:/app
      - ./spec.yml:/app/spec.yml
      # nodejs 出力先 (/generate/nodejs/xxx)
      - ../api/app/protocols:/generate/nodejs/api/
      - ../matching/app/protocols:/generate/nodejs/matching/
      - ../test/test_client/app/protocols:/generate/nodejs/test_client/
      - ../test/test_server/app/protocols:/generate/nodejs/test_server/
      # C# 出力先 (/generate/cs/xxx)
      - ../../Assets/Protocols:/generate/cs/Assets/

