FROM billyteves/ubuntu-dind:16.04
RUN apt-get update && apt-get install -y curl
RUN curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
RUN chmod 755 /usr/local/bin/docker-compose
RUN echo no | dpkg-reconfigure dash
CMD :
