# mindlink client
mindlinkClient:
  url:           ["ws://mindlink:7766/", "${MINDLINK_URL}"]
  retryCount:    [20,                    "${MINDLINK_RETRY_COUNT}"]
  retryInterval: [1000,                  "${MINDLINK_RETRY_INTERVAL}"]

# api server
apiServer:
  port: [7780, "${PORT}"]

# couch client
couchClient:
  url: ["http://couchdb:5984/db", "${COUCH_URL}"]

# redis client
redisClient:
  url: ["redis://redis:6379/?db=0", "${REDIS_URL}"]

# log4js
log4js:
  appenders:
    console:
      type: console
  categories:
    default:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    mindlinkClient:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    apiServer:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    couchClient:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    redisClient:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]

