# api server
#apiServer:

# mindlink client
mindlinkClient:
  url:           ["ws://mindlink:7766/", "${MINDLINK_URL}"]
  retryCount:    [20,                    "${MINDLINK_RETRY_COUNT}"]
  retryInterval: [1000,                  "${MINDLINK_RETRY_INTERVAL}"]

# webapi server
webapiServer:
  port: [7780, "${PORT}"]

# webapi
webapi:
  webapiServer:
    url: "http://api:7780/"
    queries:
      value: 10

# log4js
log4js:
  appenders:
    console:
      type: console
  categories:
    default:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    apiServer:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    mindlinkClient:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    webapiServer:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]

