// NOTE auto generated by 'protocols'.
module.exports = {};

// 説明
module.exports.StartGame = function() {
  return {
      sceneName: null,
      sceneNum: 10,
      isSwitch: true,
      users: [],
  };
}

// 説明
module.exports.User = function() {
  return {
      userName: null,
  };
}

