# test
#test:

# mindlink client 1
mindlinkClient1:
  url: "ws://localhost:7766/"
  retry:
    maxCount: 20

# mindlink client 2
mindlinkClient2:
  url: "ws://localhost:7767/"
  retry:
    maxCount: 20

# mindlink client 3
mindlinkClient3:
  url: "ws://localhost:7766/"
  retry:
    maxCount: 20

# log4js
log4js:
  appenders:
    console:
      type: console
  categories:
    default:
      appenders: [console]
      level: info
    test:
      appenders: [console]
      level: info
    mindlinkClient:
      appenders: [console]
      level: info
    appServer:
      appenders: [console]
      level: info

