# couch client
couchClient:
  url: ["http://couchdb:5984/db", "${COUCH_URL}"]

# redis client
redisClient:
  url: ["redis://redis:6379/", "${REDIS_URL}"]

# mindlink client
mindlinkClient:
  url:           ["ws://mindlink:7766/", "${MINDLINK_URL}"]
  retryCount:    [20,                    "${MINDLINK_RETRY_COUNT}"]
  retryInterval: [3000,                  "${MINDLINK_RETRY_INTERVAL}"]

# matching server
matchingServer:
  fqdn:    ["localhost", "${FQDN}"]
  port:    [7755,        "${PORT}"]
  timeout: [300000,      "${TIMEOUT}"]

# join queue
joinQueue:
  limit:    32
  parallel: [1, "${JOIN_QUEUE_PARALLEL}"]

# matching queue
matchingQueue:
  limit:    256
  parallel: [1, "${MATCHING_QUEUE_PARALLEL}"]

# setup queue
setupQueue:
  limit:    1
  parallel: [1, "${SETUP_QUEUE_PARALLEL}"]

# error queue
errorQueue:
  limit:    -1
  parallel: [16, "${ERROR_QUEUE_PARALLEL}"]

# setup error queue
setupErrorQueue:
  limit:    -1
  parallel: [16, "${SETUP_ERROR_QUEUE_PARALLEL}"]

# log4js
log4js:
  appenders:
    console:
      type: console
  categories:
    default:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    couchClient:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    redisClient:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    mindlinkClient:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    matchingServer:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    joinQueue:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    matchingQueue:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    setupQueue:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    errorQueue:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    setupErrorQueue:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]

