services:
  api:
    depends_on:
    - couchdb
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: fu-n.net:5000/newg-local/api@sha256:e414a203ee6851a1195949faa45745dc279a970bbcb521fb8e314e691d17bb1b
  client:
    depends_on:
    - matching
    - server
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/client@sha256:e0995deed0a45bc17589697a34fae789578857fd614d31c5cc6ec045bf88b1ae
    ports:
    - published: 80
      target: 80
  couchdb:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: couchdb@sha256:7bff6cce6812bd1fe7a9d985d1e7d27ee8351e255a66d847a231cf31384ee4ac
  matching:
    depends_on:
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/matching@sha256:b25656e7e9fb77132c87031559c1dd763321a4ec29e6e45f105fe62251bd9c87
    ports:
    - published: 7755
      target: 7755
  mindlink:
    depends_on:
    - rabbitmq
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: fu-n.net:5000/newg-local/mindlink@sha256:07e08004d3efd1d623154c98e9f3c1882d5db042561e5c8d150eabc1c176eb22
    ports:
    - published: 7766
      target: 7766
  rabbitmq:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: rabbitmq@sha256:ae2339bfd2154b10af527f0a6d98395f9047efc372f5947df53c9ad77835a6d2
  redis:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: redis@sha256:f57b2cdc24a1ab6752a738d81060a81ad9f0883fd006fd1cf1fb9bb75af584d7
  server:
    depends_on:
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/server@sha256:6850134b2eb2bcb2e12f4843c28201d72765752077c7b9ffc29760ec16214d05
version: '3.4'

