services:
  api:
    depends_on:
    - couchdb
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: fu-n.net:5000/newg-local/api@sha256:799114e3bdbdb2372cbc624d9a4b94de1f55a46074a67921f58c0cb2475c4a38
  client:
    depends_on:
    - matching
    - server
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/client@sha256:425b1927003f5b6dba56c2d1d49a5a35da83a61556469ef4d830a5fa266d55a5
    ports:
    - published: 80
      target: 80
  couchdb:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: couchdb@sha256:7bff6cce6812bd1fe7a9d985d1e7d27ee8351e255a66d847a231cf31384ee4ac
  matching:
    depends_on:
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/matching@sha256:a30e3f1446adeadbff4be809478de0c9052b722bba32d0cf0345ebdfd3fecb5f
    ports:
    - published: 7755
      target: 7755
  mindlink:
    depends_on:
    - rabbitmq
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: fu-n.net:5000/newg-local/mindlink@sha256:6325357baf4bbb745862cdbdcd2b8b8c1572ff064bc01b22b7d074417646161f
    ports:
    - published: 7766
      target: 7766
  rabbitmq:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: rabbitmq@sha256:ae2339bfd2154b10af527f0a6d98395f9047efc372f5947df53c9ad77835a6d2
  redis:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: redis@sha256:f57b2cdc24a1ab6752a738d81060a81ad9f0883fd006fd1cf1fb9bb75af584d7
  server:
    depends_on:
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/server@sha256:49280659de1f7d61863c49671f79f57c547d81467a83a3e3a30e969f274c190e
version: '3.4'

