services:
  api:
    depends_on:
    - couchdb
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: fu-n.net:5000/newg-local/api@sha256:42f2762317865ba31d330c8ccae2775f05a653189c411b5bb8c6158e44d91d2b
  client:
    depends_on:
    - matching
    - server
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/client@sha256:d11d17b377c4effad184e93e46cc6e719c86d9f00bfdee2a95cc647e2a2ffcca
    ports:
    - published: 80
      target: 80
  couchdb:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: couchdb@sha256:7bff6cce6812bd1fe7a9d985d1e7d27ee8351e255a66d847a231cf31384ee4ac
  matching:
    depends_on:
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/matching@sha256:379826d4238a0bc40c33bf0fd2c3eb7f18f19333a8a07d085b012baf80617cd1
    ports:
    - published: 7755
      target: 7755
  mindlink:
    depends_on:
    - rabbitmq
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: fu-n.net:5000/newg-local/mindlink@sha256:c59a1ba980056ec7af217ec02f6d256c26d860a695fa5c066c5b51ab073d4edc
    ports:
    - published: 7766
      target: 7766
  rabbitmq:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: rabbitmq@sha256:ae2339bfd2154b10af527f0a6d98395f9047efc372f5947df53c9ad77835a6d2
  redis:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: redis@sha256:f57b2cdc24a1ab6752a738d81060a81ad9f0883fd006fd1cf1fb9bb75af584d7
  server:
    depends_on:
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/server@sha256:d855b310c135280ee3f6d394d50a881618b9f542f79b8a0e6bd8b819d96679ef
version: '3.4'

