services:
  api:
    depends_on:
    - couchdb
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: fu-n.net:5000/newg-local/api@sha256:511c0c8bb8007d1f9945b8b6ec9c0e41c1260d5d75dad1f9e776031e427637aa
    ports:
    - published: 7780
      target: 7780
  client:
    depends_on:
    - matching
    - server
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/client@sha256:3dd4fe1f85843d294cbd7bd8662947fb13824d9517b7ebcf3f1a4c1f01e64936
    ports:
    - published: 80
      target: 80
  couchdb:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: couchdb@sha256:7bff6cce6812bd1fe7a9d985d1e7d27ee8351e255a66d847a231cf31384ee4ac
  matching:
    depends_on:
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/matching@sha256:a2874651adcd9ce3a2a1a95957e4e6d4e712ac16469615de64421864e287e68f
    ports:
    - published: 7755
      target: 7755
  mindlink:
    depends_on:
    - rabbitmq
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: fu-n.net:5000/newg-local/mindlink@sha256:21021d51816baa92423bdfc243220f4f51fc8bc25ff1a5ef8bbf49792ab9a961
  portainer:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 0
    image: portainer/portainer@sha256:c73269fd2ee84806be9e0051291f47e7a5ac0ad5842ac1dfd378dbafe22e3c93
    ports:
    - published: 19000
      target: 9000
    volumes:
    - portainer_data:/data:rw
    - \var\run\docker.sock:/var/run/docker.sock:rw
  rabbitmq:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: rabbitmq@sha256:ae2339bfd2154b10af527f0a6d98395f9047efc372f5947df53c9ad77835a6d2
  redis:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: redis@sha256:f57b2cdc24a1ab6752a738d81060a81ad9f0883fd006fd1cf1fb9bb75af584d7
  server:
    depends_on:
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/server@sha256:c2502d538a4bf7e0f6188cc0e2c47bdd06d3234ecde295bff2ad7a53a385aab0
version: '3.4'
volumes:
  portainer_data: {}

