services:
  api:
    depends_on:
    - couchdb
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: fu-n.net:5000/newg-local/api@sha256:4f4d64bef84458b427695073da07617f77580c427ab59f8921a40091c544eb30
  client:
    depends_on:
    - matching
    - server
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/client@sha256:0aa87e300ab8284ccc97675aeefb2bd9a4be1c928f7c18216b36112627388914
    ports:
    - published: 80
      target: 80
  couchdb:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: couchdb@sha256:7bff6cce6812bd1fe7a9d985d1e7d27ee8351e255a66d847a231cf31384ee4ac
  matching:
    depends_on:
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/matching@sha256:7ce47d3b92c426753d4177a7237040f8840bb7d4d823f4549c7037604a0b05c6
    ports:
    - published: 7755
      target: 7755
  mindlink:
    depends_on:
    - rabbitmq
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: fu-n.net:5000/newg-local/mindlink@sha256:e809e0478efdda8d2455ad7d56689e6b87961dda8d40aee9ccc024d06f5c9bcd
    ports:
    - published: 7766
      target: 7766
  rabbitmq:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: rabbitmq@sha256:ae2339bfd2154b10af527f0a6d98395f9047efc372f5947df53c9ad77835a6d2
  redis:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: redis@sha256:f57b2cdc24a1ab6752a738d81060a81ad9f0883fd006fd1cf1fb9bb75af584d7
  server:
    depends_on:
    - mindlink
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: fu-n.net:5000/newg-local/server@sha256:24161b87cdc3f9ab7a5ed786bb0e5d5d0ef6d48d012abad37f75aefa1b5b9b7a
version: '3.4'

