version: '3.4'
services:
  client:
    build:
      context: ./client
      args:
        - BUILD_CONFIGURATION=develop
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./client/Builds/Client:/usr/share/nginx/html
    ports:
      - 80:80

  server:
    build:
      context: ./server
      args:
        - BUILD_CONFIGURATION=develop
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./server/Builds:/server
    ports:
      - 7777:7777

  matching:
    build:
      context: ./matching
      args:
        - BUILD_CONFIGURATION=develop
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./matching/app:/app
      - ./services:/app/services
    ports:
      - 7755:7755

  api:
    build:
      context: ./api
      args:
        - BUILD_CONFIGURATION=develop
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./api/app:/app
      - ./services:/app/services
    ports:
      - 7780:7780

  mindlink:
    build:
      context: ./mindlink
      args:
        - BUILD_CONFIGURATION=develop
    environment:
      - DEBUG_HTTP_CHANNEL_ENABLE=1
      - LOG_LEVEL=debug
    volumes:
      - ./mindlink/app:/app
      - ./services:/app/services
    ports:
      - 127.0.0.1:17766:17766

  rabbitmq:
    #volumes:
    #  - ./.volumes/rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 127.0.0.1:15672:15672

  couchdb:
    volumes:
      - ./.volumes/couchdb_data:/opt/couchdb/data
    ports:
      - 127.0.0.1:15984:5984

  redis:
    volumes:
      - ./.volumes/redis_data:/data

  portainer:
    volumes:
      - ./.volumes/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:19000:9000

