version: '3.3'
services:
  client:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  server:
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  matching:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  mindlink:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  rabbitmq:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  outside:
    external:
      name: "host"
