version: '3.4'
services:
  client:
    environment:
      - FQDN=${ENV_FQDN}
    ports:
      - 7080:80
    networks:
      - inside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  server:
    environment:
      - FQDN=${ENV_FQDN}
    ports:
      - 7777:7777
    networks:
      - inside
      #- outside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  matching:
    environment:
      - FQDN=${ENV_FQDN}
      - LOG_LEVEL=debug
    ports:
      - 7755:7755
    networks:
      - inside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  api:
    environment:
      - FQDN=${ENV_FQDN}
      - LOG_LEVEL=debug
    ports:
      - 7780:7780
    networks:
      - inside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  mindlink:
    environment:
      - DEBUG_HTTP_CHANNEL_ENABLE=1
      - LOG_LEVEL=debug
    ports:
      - 127.0.0.1:17766:17766
    networks:
      - inside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  rabbitmq:
    volumes:
      - rabbitmq_data:/opt/couchdb/data/mnesia
    ports:
      - 127.0.0.1:15672:15672
    networks:
      - inside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  couchdb:
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      - 127.0.0.1:15984:5984
    networks:
      - inside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  redis:
    volumes:
      - redis_data:/data
    networks:
      - inside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  sense:
    environment:
      - DEST=http://api:7780
    ports:
      - 127.0.0.1:17780:80
    networks:
      - inside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  portainer:
    command: --no-auth
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:19000:9000
    networks:
      - inside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  rabbitmq_data:
  couchdb_data:
  redis_data:
  portainer_data:

networks:
  inside:
  #outside:
  #  external:
  #    name: "host"
