# NOTE
#    80 client   (http)
#  RAND server   (Unity Networking)
#  7755 matching (websocket)
#  7766 mindlink (websocket)
#  7780 api      (http)
#  7788 api      (websocket)
#  7799 test     (websocket)
#
#  5672 rabbitmq
#  5984 couchdb
# 15672 rabbitmq webui
# 17766 mindlink webui
#
# NOTE
# "server" はホストモードで動作する。(docker-compose.override.yml 参照)
# Docker for Win, Docker for Mac の場合は 10.0.75.2 に接続。
version: '3.3'
services:
  client:
    image: newg/client:1
    ports:
      - 80:80
    depends_on:
      - server
      - matching

  server:
    image: newg/server:1
    depends_on:
      - mindlink

  matching:
    image: newg/matching:1
    ports:
      - 7755:7755
    depends_on:
      - mindlink

  api:
    image: newg/api:1
    depends_on:
      - mindlink
      - couchdb

  mindlink:
    image: nunun/mindlink
    ports:
      - 7766:7766
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.0-alpine

  couchdb:
    image: couchdb:2.1.1

  redis:
    image: redis:4.0.6-alpine

