# NOTE
#    80 client   (http)
#  RAND server   (Unity Networking)
#  7755 matching (websocket)
#  7766 mindlink (websocket)
#  7780 api      (http)
#  7788 api      (websocket)
#  7799 test     (websocket)
#
#  5672 rabbitmq
#  5984 couchdb
# 15672 rabbitmq webui
# 17766 mindlink webui
version: '3.3'
services:
  client:
    image: ${ENV_REPOSITORY}/client
    ports:
      - 80:80
    depends_on:
      - server
      - matching

  server:
    image: ${ENV_REPOSITORY}/server
    depends_on:
      - mindlink

  matching:
    image: ${ENV_REPOSITORY}/matching
    ports:
      - 7755:7755
    depends_on:
      - mindlink

  api:
    image: ${ENV_REPOSITORY}/api
    depends_on:
      - mindlink
      - couchdb

  mindlink:
    image: ${ENV_REPOSITORY}/mindlink
    ports:
      - 7766:7766
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.0-alpine

  couchdb:
    image: couchdb:2.1.1

  redis:
    image: redis:4.0.6-alpine

