#         80 client          => http
#       7755 matching        => websocket
#       7766 mindlink        => websocket
#       7777 server          => Unity Networking (fixed port  for debug)
#  8000-9999 server          => Unity Networking (random port for service)
#       7780 api             => http
#       7788 api             => websocket
#       7799 test            => websocket
#       5672 rabbitmq        => rabbitmq
#       5984 couchdb         => couchdb
#      15672 rabbitmq  webui => http://localhost:15672
#      15984 rabbitmq  webui => http://localhost:15984/_utils
#      17766 mindlink  webui => http://localhost:17766
#      17780 sense     webui => http://localhost:17780
#      19000 portainer webui => http://localhost:19000
version: '3.4'
services:
  client:
    image: ${ENV_REPOSITORY}/client
    depends_on:
      - server
      - matching

  server:
    image: ${ENV_REPOSITORY}/server
    depends_on:
      - mindlink

  matching:
    image: ${ENV_REPOSITORY}/matching
    depends_on:
      - mindlink

  api:
    image: ${ENV_REPOSITORY}/api
    depends_on:
      - mindlink
      - couchdb

  mindlink:
    image: ${ENV_REPOSITORY}/mindlink
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.0-management-alpine

  couchdb:
    image: couchdb:2.1.1

  redis:
    image: redis:4.0.6-alpine

  sense:
    image: nunun/sense

  portainer:
    image: portainer/portainer

