version: '3.4'
services:
  client:
    build:
      context: ./client
      dockerfile: ./../services/Dockerfile.client
    environment:
      - FQDN=${ENV_FQDN}
      - LOG_LEVEL=debug
    volumes:
      - ./client/Builds/Client:/usr/share/nginx/html
    ports:
      - 7080:80

  server:
    build:
      context: ./server
      dockerfile: ./../services/Dockerfile.server
    environment:
      - FQDN=${ENV_FQDN}
      - LOG_LEVEL=debug
    volumes:
      - ./server:/server
    ports:
      - 7777:7777
      - 7778:7778/udp
      - 127.0.0.1:17777:17777

  matching:
    build:
      context: ./matching
      dockerfile: ./../services/Dockerfile.node.develop
    environment:
      - FQDN=${ENV_FQDN}
      - LOG_LEVEL=debug
    volumes:
      - ./matching:/app
      - ./services:/app/services
    ports:
      - 7755:7755

  api:
    build:
      context: ./api
      dockerfile: ./../services/Dockerfile.node.develop
    environment:
      - FQDN=${ENV_FQDN}
      - LOG_LEVEL=debug
    volumes:
      - ./api:/app
      - ./services:/app/services
    ports:
      - 7780:7780

  mindlink:
    build:
      context: ./mindlink
      dockerfile: ./../services/Dockerfile.node.develop
    environment:
      - DEBUG_HTTP_CHANNEL_ENABLE=1
      - LOG_LEVEL=debug
    volumes:
      - ./mindlink:/app
      - ./services:/app/services
    ports:
      - 127.0.0.1:7766:7766
      - 127.0.0.1:17766:17766

  rabbitmq:
    volumes:
      - ./.volumes/rabbitmq_data:/var/lib/rabbitmq/mnesia
    ports:
      - 127.0.0.1:15672:15672

  couchdb:
    volumes:
      - ./.volumes/couchdb_data:/opt/couchdb/data
    ports:
      - 127.0.0.1:15984:5984

  redis:
    volumes:
      - ./.volumes/redis_data:/data

  sense:
    environment:
      - DEST=http://api:7780
    ports:
      - 127.0.0.1:17780:80

  portainer:
    command: --no-auth
    volumes:
      - ./.volumes/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:19000:9000

