version: '3.4'
services:
  client:
    build:
      context: ./client
      args:
        - BUILD_CONFIGURATION=develop
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./client/Builds/Client:/usr/share/nginx/html
    ports:
      - 80:80

  server:
    build:
      context: ./server
      args:
        - BUILD_CONFIGURATION=develop
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./server/Builds:/server
    ports:
      - 7777:7777

  matching:
    build:
      context: ./matching
      args:
        - BUILD_CONFIGURATION=develop
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./matching/app:/app
      - ./services:/app/services
    ports:
      - 7755:7755

  api:
    build:
      context: ./api
      args:
        - BUILD_CONFIGURATION=develop
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./api/app:/app
      - ./services:/app/services
    ports:
      - 7780:7780

  mindlink:
    build:
      context: ./mindlink
      args:
        - BUILD_CONFIGURATION=develop
    environment:
      - DEBUG_HTTP_CHANNEL_ENABLE=1
      - LOG_LEVEL=debug
    volumes:
      - ./mindlink/app:/app
      - ./services:/app/services
    ports:
      - 17766:17766

  rabbitmq:
    image: rabbitmq:3.7.0-management-alpine
    ports:
      - 15672:15672

  couchdb: {}

  redis: {}

  portainer:
    volumes:
      - ./.volumes/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 19000:9000

