# NOTE
#    80 client   (http)
#  7755 matching (websocket)
#  7766 mindlink (websocket)
#  7777 server   (Unity Networking (fixed port for debug))
#  7780 api      (http)
#  7788 api      (websocket)
#  7799 test     (websocket)
#
#  8000-9999 server (Unity Networking (random port for service))
#
#  5672 rabbitmq
#  5984 couchdb
# 15672 rabbitmq webui
# 17766 mindlink webui
# 19000 portainer
version: '3.4'
services:
  client:
    image: ${ENV_REPOSITORY}/client
    depends_on:
      - server
      - matching

  server:
    image: ${ENV_REPOSITORY}/server
    depends_on:
      - mindlink

  matching:
    image: ${ENV_REPOSITORY}/matching
    depends_on:
      - mindlink

  api:
    image: ${ENV_REPOSITORY}/api
    depends_on:
      - mindlink
      - couchdb

  mindlink:
    image: ${ENV_REPOSITORY}/mindlink
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.0-alpine

  couchdb:
    image: couchdb:2.1.1

  redis:
    image: redis:4.0.6-alpine

  portainer:
    image: portainer/portainer

