# matching server
matchingServer:
  port: [7755, "${PORT}"]
  timeout: 300000

# mindlink client
mindlinkClient:
  url:           ["ws://mindlink:7766/", "${MINDLINK_URL}"]
  retryCount:    [20,                    "${MINDLINK_RETRY_COUNT}"]
  retryInterval: [3000,                  "${MINDLINK_RETRY_INTERVAL}"]

# log4js
log4js:
  appenders:
    console:
      type: console
  categories:
    default:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    matchingServer:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
    mindlinkClient:
      appenders: [console]
      level: [info, "${LOG_LEVEL}"]
