// auto generated by protocols.
module.exports = {};

// 
module.exports.StartGame = function() {
  return {
      sceneName: null,
      sceneNum: 10,
      isSwitch: true,
      users: [],
  };
}

// 
module.exports.User = function() {
  return {
      userName: null,
  };
}

